require: rubocop-rails
AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'coverage/**/*'
    - 'db/**/*'
    - 'lib/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'spec/**/*'
    - 'vendor/**/*'
    - './*'
    - 'app/controllers/graphql_controller.rb'
    - 'node_modules/**/*'
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false

